#1.Create a table class. Fields are name and id

  CREATE TABLE CLASS(
  ID INT PRIMARY KEY NOT NULL,
  NAME VARCHAR(15) NOT NULL);

#2.Insert values into the table

  INSERT INTO CLASS VALUES(1,'MARK'),(2,'JOHNNY') ,(3,'JAY');

#3.Display the table

  SELECT * FROM CLASS;

#4.Apply commit, save point and rollback commands.

  #COMMIT command

  START TRANSACTION;
  INSERT INTO CLASS VALUES(4,'EMI');
  COMMIT;
  SELECT * FROM CLASS;

  #SAVEPOINT command

  START TRANSACTION;
  UPDATE CLASS SET NAME='JENO' WHERE ID=4;
  SAVEPOINT A;
  INSERT INTO CLASS VALUES(5,'TEN');
  SAVEPOINT B;
  INSERT INTO CLASS VALUES(6,'LUCAS');
  SAVEPOINT C;
  
  SELECT * FROM CLASS;

  ROLLBACK TO B;
  SELECT * FROM CLASS;
  ROLLBACK TO A;
  SELECT * FROM CLASS;
  COMMIT;

  #ROLLBACK command

  START TRANSACTION;
  UPDATE CLASS SET NAME='HENDERY' WHERE ID=1;
  SELECT * FROM CLASS;
  ROLLBACK;
  SELECT * FROM CLASS;
  COMMIT;


