#1.Create table EMPLOYEEDETAILS with EMPID references to the EMPID in EMPLOYEE table.
  #Create table EMPLOYEE
	CREATE TABLE EMPLOYEE(
     	EMPID VARCHAR(40) UNIQUE PRIMARY KEY NOT NULL,
    	NAME VARCHAR(10) NOT NULL,
    	DESIGNATION VARCHAR(30) NOT NULL,
    	DOB DATE NOT NULL,
    	SALARY DECIMAL NOT NULL);
	
  #Inserting value to EMPLOYEE table
	INSERT INTO EMPLOYEE VALUES('E1','JOHNNY','MANAGER','1995-02-09',50000); 
	INSERT INTO EMPLOYEE VALUES('E2','MARK','ANALYST','1999-08-02' ,25000);
	INSERT INTO EMPLOYEE VALUES('E3','JAY','SALESMAN','1997-02-12',20000); 
	INSERT INTO EMPLOYEE VALUES('E4','HENDREY','CLERK','1999-09-28',15000);

  #Create table EMPLOYEEDETAILS
	CREATE TABLE EMPLOYEEDETAILS(
	EMPID VARCHAR(40),
	ADDRESS VARCHAR(40) NOT NULL,
	GENDER VARCHAR(10),
	DOJ DATE NOT NULL,
	FOREIGN KEY(EMPID) REFERENCES EMPLOYEE(EMPID));

  #Insert values into EMPLOYEEDEATILS TABLE

	INSERT INTO EMPLOYEEDETAILS VALUES('E1' , 'USA' , 'M' , '2008-02-02');
	INSERT INTO EMPLOYEEDETAILS VALUES('E2' , 'CANADA' , 'M' , '2014-01-01');
	INSERT INTO EMPLOYEEDETAILS VALUES('E3' , 'INDIA' , 'F' , '2012-04-02');

#2.Display the details of employee table where EMPID in EMPLOYEEDEATILS table.

	SELECT *
	FROM EMPLOYEE
	WHERE EMPID IN (SELECT EMPID FROM EMPLOYEEDETAILS);

#3.Display the details of employee table where EMPID not in EMPLOYEEETAILS table

	SELECT *
	FROM EMPLOYEE
	WHERE EMPID NOT IN (SELECT EMPID FROM EMPLOYEEDETAILS);

