
# Write a database trigger that prevents changes to emp table from 5pm to 12am(statement level trigger)

# Create table EMPLOYEE
   CREATE TABLE EMPLOYEE (EMPID CHAR(4),NAME CHAR(50),DOB DATE NOT NULL,DESIGNATION CHAR(30),SALARY INT);

   INSERT INTO EMPLOYEE VALUES('E1','JOHNY','1995-02-09','MANAGER',50000); 
   INSERT INTO EMPLOYEE VALUES('E2','MARK','1999-08-02' ,'ANALYST',25000);
   INSERT INTO EMPLOYEE VALUES('E3','JAY','1997-02-12','SALESMAN',20000); 
   INSERT INTO EMPLOYEE VALUES('E4','HENDREY','1999-09-28','CLERK',15000);
   INSERT INTO EMPLOYEE VALUES('E5','LUCAS','1999-08-28','CLERK',18000);


   DELIMITER //
   CREATE TRIGGER INSERT_PREVENT
   BEFORE INSERT
   ON EMPLOYEE FOR EACH ROW
   BEGIN
	IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
	   SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
	END IF;
   END //
   DELIMITER ;

   DELIMITER //
   CREATE TRIGGER UPDATE_PREVENT
   BEFORE UPDATE
   ON EMPLOYEE FOR EACH ROW
   BEGIN
	 IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
	   SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
	END IF;
   END //
   DELIMITER ;

   DELIMITER //
   CREATE TRIGGER DELETE_PREVENT
   BEFORE DELETE
   ON EMPLOYEE FOR EACH ROW
   BEGIN
	IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
	   SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
	END IF;
   END //
   DELIMITER ;
